<!-- BEGIN (write your solution here) -->

<?php
$mesName = array_key_exists('name', $errors) ? $errors['name'] : '';
$mesBody = array_key_exists('body', $errors) ? $errors['body'] : '';
$valName = $post['name'] === '' ? '' : $post['name'];
$valBody = $post['body'] === '' ? '' : $post['body'];
?>
	<label>
	name
	<?= $mesName?>
	<input type="text" name="post[name]" value="<?= $valName ?>">
	</label>
	<label>
	body
	<?= $mesBody?>
	<input type="text" name="post[body]" value="<?= $valBody ?>">
	</label>

<!-- END -->
