<?php if (count($flash) > 0): ?> 
  <ul> 
  <?php foreach ($flash as $messages): ?> 
      <?php foreach ($messages as $message): ?> 
          <li><?= $message ?></li> 
      <?php endforeach ?> 
  <?php endforeach ?> 
  </ul> 
<?php endif ?> 


<!-- BEGIN (write your solution here) -->
<?php if(!isset($_SESSION['userName'])) {?>
<form action="/session" method="post"> 
  <div> 
    <label>
        Имя 
      <input type="text" name="user[name]"> 
    </label> 
  </div> 
  <div> 
    <label> 
        Пароль 
    <input type="password" required name="user[password]"> 
    </label> 
    </div> 
  <input type="submit" value="Sign In"> 
 <?php } else { ?>
<form action="/session" method="post"> 
    <input type="hidden" name="_METHOD" value="delete">
  <div> 
    <label>
        Имя 
      <input type="text" name="user[name]" value=<?= $_SESSION['userName'] ?>> 
    </label> 
  </div> 
  <input type="submit" value="Sign Out"> 
 <?php } ?>


<!-- END -->

