
<!-- BEGIN (write your solution here) -->
<!-- templates/users/new.phtml -->
<form action="/courses" method="post">
  <div>
    <label>
        Название курса
      <input type="text" name="course[title]" value=<?= isset($cours['title']) ? htmlspecialchars($cours['title']) : ''; ?>>
    </label>
  </div>
  <div>
    <label>
        Платность
        <select name="course[paid]">
            <option value="">Select</option>
            <option <?= isset($cours['paid']) && $cours['paid'] === 'true' ? 'selected' : '' ?> value="true">Платный</option>
            <option <?= isset($cours['paid']) && $cours['paid'] === 'false' ? 'selected' : '' ?> value="false">Безплатный</option>
        </select>
    </label>
  </div>
  <input type="submit" value="Sign Up">
</form>

<div>
    <?= empty($errors) ? "" : "Can't be blank" ?>
</div>
<!-- END -->

